targets:
  $default:
    sources:
      - lib/**
    builders:
      artemis:
        options:
           schema_mapping:
            - schema: lib/schema/pokemon.graphql
              output: lib/pokemon_api.dart
              queries_glob: lib/query/**.graphql
              fragments_glob: lib/fragments/**.graphql